persistence true
persistence_location /mosquitto/data/
log_dest stdout
log_type warning
log_type notice
listener 8883
allow_anonymous false
password_file /tmp/passwords
acl_file /mosquitto/config/acl
cafile /run/tls/ca.crt
certfile /run/tls/server.crt
keyfile /run/tls/server.key
tls_version tlsv1.2
max_packet_size 16384
max_queued_messages 120
message_size_limit 8192
